/** Small exact and approximate tests used by the pilot table and the power simulation. No dependencies. */
export function wilson(k: number, n: number, z = 1.96) { if (!n) return { p: 0, lo: 0, hi: 0 }; const p = k / n; const den = 1 + (z * z) / n; const c = (p + (z * z) / (2 * n)) / den; const h = (z * Math.sqrt((p * (1 - p)) / n + (z * z) / (4 * n * n))) / den; return { p, lo: Math.max(0, c - h), hi: Math.min(1, c + h) }; }
function lnFact(n: number) { let s = 0; for (let i = 2; i <= n; i++) s += Math.log(i); return s; }
function lnChoose(n: number, k: number) { return lnFact(n) - lnFact(k) - lnFact(n - k); }
/** Two-sided exact binomial test of k successes in n at p = 0.5 (McNemar on discordant pairs). */
export function binomTwoSided(k: number, n: number): number { if (n === 0) return 1; const pk = (i: number) => Math.exp(lnChoose(n, i) - n * Math.LN2); const pObs = pk(k); let p = 0; for (let i = 0; i <= n; i++) if (pk(i) <= pObs + 1e-12) p += pk(i); return Math.min(1, p); }
/** Fisher exact two-sided on [[a,b],[c,d]] (a,b successes and failures in group 1; c,d in group 2). */
export function fisherTwoSided(a: number, b: number, c: number, d: number): number { const r1 = a + b, r2 = c + d, c1 = a + c, n = r1 + r2; const lnP = (x: number) => lnChoose(r1, x) + lnChoose(r2, c1 - x) - lnChoose(n, c1); const pObs = Math.exp(lnP(a)); let p = 0; for (let x = Math.max(0, c1 - r2); x <= Math.min(r1, c1); x++) { const px = Math.exp(lnP(x)); if (px <= pObs * (1 + 1e-9)) p += px; } return Math.min(1, p); }
/** Cochran-Armitage trend test for proportions across ordered groups (independent-groups form; the paired structure is ignored, which is conservative here only in the sense that it wastes pairing). */
export function cochranArmitage(counts: Array<{ k: number; n: number; score: number }>): { z: number; p: number } { const N = counts.reduce((a, g) => a + g.n, 0); const K = counts.reduce((a, g) => a + g.k, 0); if (!N || !K || K === N) return { z: 0, p: 1 }; const pbar = K / N; const sbar = counts.reduce((a, g) => a + g.n * g.score, 0) / N; const T = counts.reduce((a, g) => a + g.score * (g.k - g.n * pbar), 0); const V = pbar * (1 - pbar) * counts.reduce((a, g) => a + g.n * (g.score - sbar) ** 2, 0); const z = V > 0 ? T / Math.sqrt(V) : 0; return { z, p: 2 * (1 - normCdf(Math.abs(z))) }; }
export function normCdf(x: number) { const t = 1 / (1 + 0.2316419 * Math.abs(x)); const d = 0.3989423 * Math.exp(-x * x / 2); const p = d * t * (0.3193815 + t * (-0.3565638 + t * (1.781478 + t * (-1.821256 + t * 1.330274)))); return x > 0 ? 1 - p : p; }
/** One-way ANOVA intraclass correlation for a binary indicator with k groups of equal size m. */
export function icc1(groups: number[][]): number | null { const k = groups.length; if (k < 2) return null; const m = groups[0]!.length; const N = k * m; const all = groups.flat(); const gm = all.reduce((a, b) => a + b, 0) / N; if (gm === 0 || gm === 1) return null; const means = groups.map((g) => g.reduce((a, b) => a + b, 0) / g.length); const msb = groups.reduce((a, g, i) => a + g.length * (means[i]! - gm) ** 2, 0) / (k - 1); const msw = groups.reduce((a, g, i) => a + g.reduce((s, y) => s + (y - means[i]!) ** 2, 0), 0) / (N - k); return (msb - msw) / (msb + (m - 1) * msw); }
/** Holm step-down: returns adjusted p-values in the original order. */
export function holm(ps: number[]): number[] { const idx = ps.map((p, i) => [p, i] as const).sort((a, b) => a[0] - b[0]); const m = ps.length; const adj = new Array(m).fill(0); let run = 0; idx.forEach(([p, i], r) => { run = Math.max(run, Math.min(1, (m - r) * p)); adj[i] = run; }); return adj; }
