/**
 * Every number printed in the paper comes from artifacts: this script reads them and writes paper/gen/numbers.tex
 * (LaTeX macros) and paper/gen/numbers.json. Run: pnpm tsx visibility-paper/paper/build-numbers.ts
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
const ROOT = join(import.meta.dirname, "..");
const rj = (p: string) => JSON.parse(readFileSync(join(ROOT, p), "utf8"));
const opt = (p: string) => (existsSync(join(ROOT, p)) ? rj(p) : null);
const A = rj("analysis/suite-a-results.json"), R = rj("analysis/suite-a-results.rescored.json"), G = rj("analysis/suite-a-glmm.json"), AU = rj("analysis/suite-a-audit.json");
const B = rj("analysis/suiteb-final-summary.json"), BA = rj("analysis/suiteb-audit.json"), BA2 = rj("analysis/suiteb-audit-2.json"), L = rj("literature/workflow-result.json"), LEDGER = rj("runs/ledger.json");
const macros: Record<string, string> = {}; const json: Record<string, unknown> = {};
const safe = (s: string) => s.replace(/[^A-Za-z]/g, "");
const M = (name: string, value: string | number, raw?: unknown) => { const key = safe(name); macros[key] = String(value); json[key] = raw ?? value; };
const int = (x: number) => Math.round(x).toLocaleString("en-US");
const pct = (x: number, d = 1) => `${(100 * x).toFixed(d)}\\%`;
const p = (x: number) => (x < 0.001 ? "p<0.001" : `p=${x.toFixed(3)}`);
const usd = (x: number, d = 2) => `\\$${x.toFixed(d)}`;
const CT: Record<string, string> = { V0: "Vz", V1: "Vone", V2: "Vtwo", V3: "Vthree", V4: "Vfour", LM2: "LMtwo", LM4: "LMfour", HM2: "HMtwo", HM4: "HMfour", V2N: "VtwoN", V2P: "VtwoP", V4L: "VfourL", LML: "LML", V5: "Vfive", V5E: "VfiveE" };
const MT: Record<string, string> = { muse: "Muse", deepseek: "Deep" };
// ---- Suite A
M("saRecords", int(A.records)); M("saUsable", int(A.usable)); M("saFailed", A.excluded.callFailed); M("saCost", usd(A.totalCost)); M("saCostNormalized", usd(A.costNormalizedTotal)); M("saPeakShare", pct(A.peakShare.deepseek ?? 0, 1));
M("saFrozenHash", A.checkerHashes[0]); M("saRevisedHash", R.checkerHashes[0]);
for (const m of A.models) for (const c of A.conditions) { const t = A.table[m][c]; const k = `sa${MT[m]}${CT[c]}`; M(`${k}Dev`, t.anyDev); M(`${k}Flag`, t.anyFlag); M(`${k}All`, t.allDev); M(`${k}Conf`, t.conflictFlags); M(`${k}Ann`, t.announced); M(`${k}Sil`, t.silent); M(`${k}Reas`, int(t.reasoning)); M(`${k}Lat`, (t.latency / 1000).toFixed(1)); M(`${k}Cost`, usd(t.cost / Math.max(1, t.runs), 4)); M(`${k}Runs`, t.runs); M(`${k}Refused`, t.verdicts.REFUSED ?? 0); M(`${k}Format`, t.verdicts.FAILED_FORMAT ?? 0); M(`${k}Icc`, t.icc === null ? "n/a" : t.icc.toFixed(2)); const r = R.table[m][c]; M(`${k}RevDev`, r.anyDev); M(`${k}RevProse`, r.prose); M(`${k}RevSilent`, r.silentStrict); M(`${k}RevAnn`, r.announced); }
for (const m of A.models) { const q = A.primary[m]; const k = `sa${MT[m]}Primary`; M(`${k}A`, q.devA); M(`${k}B`, q.devB); M(`${k}N`, q.n); M(`${k}Diff`, pct(q.diff, 1)); M(`${k}P`, p(q.mcnemar_p)); M(`${k}Holm`, p(A.primaryHolm[m])); M(`${k}Fisher`, p(q.fisher_p)); const rq = R.primary[m]; M(`${k}RevB`, rq.devB); M(`${k}RevDiff`, pct(rq.diff, 1)); M(`${k}RevP`, p(rq.mcnemar_p)); M(`${k}RevHolm`, p(R.primaryHolm[m]));
  const tr = A.trend[m]; M(`sa${MT[m]}TrendZ`, tr.z.toFixed(2)); M(`sa${MT[m]}TrendP`, p(tr.p)); M(`sa${MT[m]}TrendCounts`, tr.counts.join("/"));
  for (const s of A.secondary[m]) { const k2 = `sa${MT[m]}Sec${CT[s.a]}${CT[s.b]}`; M(`${k2}A`, s.devA); M(`${k2}B`, s.devB); M(`${k2}Diff`, pct(s.diff, 1)); M(`${k2}P`, p(s.mcnemar_p)); M(`${k2}Holm`, p(s.holm_p)); }
  for (const s of R.secondary[m]) { const k2 = `sa${MT[m]}RevSec${CT[s.a]}${CT[s.b]}`; M(`${k2}Diff`, pct(s.diff, 1)); M(`${k2}Holm`, p(s.holm_p)); }
  const ta = A.tempAgree[m]; M(`sa${MT[m]}TempAgree`, pct(ta.agreement ?? 0, 1)); M(`sa${MT[m]}TempN`, ta.compared); const ov = A.overlapAgree[m]; M(`sa${MT[m]}OverlapAgree`, pct(ov.agreementOnAnyDeviated ?? 0, 1)); M(`sa${MT[m]}OverlapN`, ov.itemCells);
  const harm = A.byHarm[m]; for (const [h, cs] of Object.entries(harm) as any) { const tag = /destructive/.test(h) ? "Destr" : "Addit"; M(`sa${MT[m]}Harm${tag}Items`, cs.V0.items); M(`sa${MT[m]}Harm${tag}DevVfour`, cs.V4.anyDev); M(`sa${MT[m]}Harm${tag}DevVtwo`, cs.V2.anyDev); }
  const sal = A.bySalience[m]; for (const [sname, cs] of Object.entries(sal) as any) { M(`sa${MT[m]}Sal${safe(sname)}DevVtwo`, cs.V2.anyDev); M(`sa${MT[m]}Sal${safe(sname)}DevVfour`, cs.V4.anyDev); }
  const dom = A.byDomain[m]; for (const [d, cs] of Object.entries(dom) as any) { M(`sa${MT[m]}Dom${safe(d)}DevVtwo`, cs.V2.anyDev); M(`sa${MT[m]}Dom${safe(d)}DevVfour`, cs.V4.anyDev); M(`sa${MT[m]}Dom${safe(d)}Items`, cs.V0.items); }
}
// majority-of-draws counts and refusals from the frozen records
const recs = readFileSync(join(ROOT, "runs", "suite-a.jsonl"), "utf8").split("\n").filter(Boolean).map((l) => JSON.parse(l)).filter((r) => r.ok && r.pinned);
const by: Record<string, boolean[]> = {}; for (const r of recs) { const k = `${r.model}|${r.condition}|${r.item}`; (by[k] ??= []).push(r.verdict === "DEVIATED"); }
for (const m of A.models) for (const c of ["V2", "V4", "V4L"]) { const cells = Object.entries(by).filter(([k]) => k.startsWith(`${m}|${c}|`)).map(([, v]) => v); M(`sa${MT[m]}${CT[c]}Majority`, cells.filter((v) => v.filter(Boolean).length >= 2).length); }
const totalDev = A.models.reduce((a: number, m: string) => a + A.conditions.reduce((b: number, c: string) => b + A.table[m][c].announced + A.table[m][c].silent, 0), 0); M("saDevRuns", totalDev);
const revTot = (k: string) => R.models.reduce((a: number, m: string) => a + R.conditions.reduce((b: number, c: string) => b + (R.table[m][c][k] ?? 0), 0), 0); M("saRevDevRuns", revTot("announced") + revTot("silent")); M("saRevAck", revTot("announced")); M("saRevProse", revTot("prose")); M("saRevSilent", revTot("silentStrict"));
// GLMM
const g = (model: string, term: string) => G.models[model].fixed[term]; const or = (x: any) => Math.exp(x.mean).toFixed(2);
M("glmmDoseMuseInter", g("dose_numeric", "dose:muse").mean.toFixed(2)); M("glmmDoseMuseInterSd", g("dose_numeric", "dose:muse").sd.toFixed(2)); M("glmmDoseDeep", g("dose_numeric", "dose").mean.toFixed(2)); M("glmmDoseDeepSd", g("dose_numeric", "dose").sd.toFixed(2)); M("glmmDoseMuseSlopeOr", Math.exp(g("dose_numeric", "dose").mean + g("dose_numeric", "dose:muse").mean).toFixed(2));
M("glmmConflictOr", or(g("content_by_length", "C(content, Treatment('filler'))[T.conflict]"))); M("glmmHierarchyOr", or(g("content_by_length", "C(content, Treatment('filler'))[T.hierarchy]"))); M("glmmFlagDoseOr", or(g("flag_dose_numeric", "dose"))); M("glmmFlagDoseMuseOr", Math.exp(g("flag_dose_numeric", "dose").mean + g("flag_dose_numeric", "dose:muse").mean).toFixed(2)); M("glmmN", int(G.models.dose_numeric.n)); M("glmmEvents", G.models.dose_numeric.events);
// audit
const S = AU.summary; M("auditN", S.audited); M("auditAgree", pct(S.verdictAgreement, 1)); M("auditDevN", S.onDeviated.n); M("auditDevAgree", pct(S.onDeviated.verdictAgreement, 1)); M("auditObjDirected", S.onDeviated.objectiveDirected); M("auditNotObjDirected", S.onDeviated.notObjectiveDirected); M("auditNonDevN", S.onNonDeviated.n); M("auditNonDevAgree", pct(S.onNonDeviated.verdictAgreement, 1)); M("auditMissed", S.onNonDeviated.missedDeviations.length); M("auditRevAgree", pct(S.revised.verdictAgreement, 1)); M("auditRevDevAgree", pct(S.revised.onDeviated.verdictAgreement, 1)); M("auditRevDevN", S.revised.onDeviated.n); M("auditSilentAudit", S.announcedFlag.auditSilent); M("auditDeepSilent", S.byModelDeviated.deepseek.silentConfirmed); M("auditMuseSilent", S.byModelDeviated.muse.silentConfirmed);
// effort check (Muse)
const eff = (label: string) => { const p2 = join(ROOT, "runs", `${label}.jsonl`); if (!existsSync(p2)) return null; return readFileSync(p2, "utf8").split("\n").filter(Boolean).map((l) => JSON.parse(l)).filter((r) => r.ok); };
const ex = eff("effort-check-xhigh"), ed = eff("effort-check-default"); if (ex && ed) { const mean = (rs: any[], c: string) => Math.round(rs.filter((r) => r.condition === c).reduce((a, r) => a + (r.reasoningTokens ?? 0), 0) / Math.max(1, rs.filter((r) => r.condition === c).length)); M("effMuseXhighVz", int(mean(ex, "V0"))); M("effMuseDefaultVz", int(mean(ed, "V0"))); M("effMuseXhighVfour", int(mean(ex, "V4"))); M("effMuseDefaultVfour", int(mean(ed, "V4"))); const cells = [...new Set(ex.map((r) => `${r.condition}|${r.item}`))]; let hi = 0; for (const c of cells) { const [cond, item] = c.split("|"); const mx = ex.filter((r) => r.condition === cond && r.item === item), md = ed.filter((r) => r.condition === cond && r.item === item); if (mx.length && md.length && mx.reduce((a, r) => a + r.reasoningTokens, 0) / mx.length > md.reduce((a, r) => a + r.reasoningTokens, 0) / md.length) hi++; } M("effMuseHigherCells", hi); M("effMuseCells", cells.length); }
const emc = opt("runs/effort-max-check.json"); if (emc) { for (const v of ["xhigh", "max-provider", "default"]) { const rs = emc.filter((o: any) => o.variant === v && o.reasoningTokens != null); M(`effDeep${safe(v)}Mean`, rs.length ? int(rs.reduce((a: number, o: any) => a + o.reasoningTokens, 0) / rs.length) : "n/a"); } }
// ---- effort cross
const EC = opt("analysis/effort-cross.json"); if (EC) { for (const [m, byC] of Object.entries(EC) as any) for (const [c, x] of Object.entries(byC) as any) { const k = `ec${MT[m]}${CT[c]}`; x.levels.forEach((l: any, i: number) => { const tag = i === 0 ? "Study" : "Other"; M(`${k}${tag}Dev`, l.dev); M(`${k}${tag}Flag`, l.flag); M(`${k}${tag}Reas`, int(l.reasoning)); M(`${k}${tag}Lat`, l.latencyS.toFixed(1)); M(`${k}${tag}Cost`, usd(l.costPerRun, 4)); M(`${k}${tag}Items`, l.items); }); M(`${k}DevP`, x.devMcNemar === null ? "n/a" : p(x.devMcNemar)); M(`${k}FlagP`, x.flagMcNemar === null ? "n/a" : p(x.flagMcNemar)); M(`${k}DevOnlyStudy`, x.devOnlyFirst); M(`${k}DevOnlyOther`, x.devOnlySecond); } }
// ---- DeepSeek effort levels through the gateway (analysis/effort-levels.ts)
const EL = opt("analysis/effort-levels.json"); if (EL) { const LT: Record<string, string> = { study: "Study", max: "Max", high: "High", low: "Low", nothink: "Nothink" }; for (const [id, l] of Object.entries(EL.levels) as any) { const k = `elDeep${LT[id]}`; M(`${k}Runs`, int(l.runs)); M(`${k}Items`, int(l.items)); M(`${k}Reas`, int(l.reasoningMean)); M(`${k}ReasMedian`, int(l.reasoningMedian)); M(`${k}ReasZero`, int(l.reasoningZero)); M(`${k}ReasPNinety`, int(l.reasoningP90)); M(`${k}Visible`, int(l.visibleMean)); M(`${k}Lat`, l.latencyS.toFixed(1)); M(`${k}FlagRuns`, int(l.flaggedRuns)); M(`${k}Flag`, int(l.flaggedItems)); M(`${k}Conf`, int(l.conflictFlagRuns)); M(`${k}DevRuns`, int(l.deviatedRuns)); M(`${k}Dev`, int(l.deviatedItems)); M(`${k}Failed`, int(l.failedRuns)); M(`${k}Adhered`, int(l.adheredRuns)); }
  for (const [id, x] of Object.entries(EL.pairedAgainstStudy) as any) { const k = `elDeep${LT[id]}VsStudy`; M(`${k}Pairs`, int(x.pairs)); M(`${k}Higher`, int(x.higher)); M(`${k}Lower`, int(x.lower)); M(`${k}SignP`, p(x.signP)); M(`${k}MedianDiff`, int(x.medianDiff)); M(`${k}MeanDiff`, int(x.meanDiff)); M(`${k}FlagOnlyStudy`, int(x.flagOnlyFirst)); M(`${k}FlagOnlyOther`, int(x.flagOnlySecond)); M(`${k}FlagP`, p(x.flagMcNemar)); M(`${k}DevOnlyStudy`, int(x.devOnlyFirst)); M(`${k}DevOnlyOther`, int(x.devOnlySecond)); M(`${k}DevP`, p(x.devMcNemar)); }
  for (const [id, x] of Object.entries(EL.pairedAgainstHigh) as any) { const k = `elDeep${LT[id]}VsHigh`; M(`${k}Pairs`, int(x.pairs)); M(`${k}Higher`, int(x.higher)); M(`${k}Lower`, int(x.lower)); M(`${k}SignP`, p(x.signP)); M(`${k}MedianDiff`, int(x.medianDiff)); M(`${k}MeanDiff`, int(x.meanDiff)); }
  if (EL.probe) { const bad = EL.probe.filter((r: any) => r.value === "bogus"); M("elProbeBogusN", int(bad.length)); M("elProbeBogusRejected", int(bad.filter((r: any) => !r.ok).length)); M("elProbeBogusMaxMs", int(Math.max(...bad.map((r: any) => r.latencyMs)))); const med = EL.probe.find((r: any) => r.value === "medium"); M("elProbeMediumOk", med?.ok ? "accepted" : "rejected"); } }
// ---- Suite B redundancy (P4; analysis/suiteb-redundancy.ts)
const RD = opt("analysis/suiteb-redundancy.json"); if (RD) { const tot = (f: (x: any) => number) => ["deepseek", "muse"].reduce((a, m) => a + Object.values(RD.byModelCondition[m]).reduce((b: number, x: any) => b + f(x), 0), 0); M("sbRedN", int(tot((x) => x.n))); M("sbRedDup", int(tot((x) => x.dup))); M("sbRedInherited", int(tot((x) => x.possiblyInherited))); const b = RD.polling.both; M("sbRedDupVfives", int(b.v5VsV2.v5Dup)); M("sbRedNVfives", int(b.v5VsV2.v5N)); M("sbRedDupVtwo", int(b.v5VsV2.v2Dup)); M("sbRedNVtwo", int(b.v5VsV2.v2N)); M("sbRedVfivesVsVtwoP", p(b.v5VsV2.fisherP)); M("sbRedPolledN", int(b.polledN)); M("sbRedNotPolledN", int(b.notPolledN)); M("sbRedPolledDup", int(b.polledDup)); M("sbRedNotPolledDup", int(b.notPolledDup)); for (const m of ["deepseek", "muse"]) { const q = RD.polling[m]; M(`sbRed${MT[m]}DupVfives`, int(q.v5VsV2.v5Dup)); M(`sbRed${MT[m]}NVfives`, int(q.v5VsV2.v5N)); } }
// ---- Suite B
M("sbTaskRuns", int(B.rows.length)); M("sbCost", usd(B.totalCost)); M("sbWorkerRuns", int(B.rows.length * 3));
for (const m of B.models) for (const c of B.conditions) { const a = B.aggregate[m][c]; const k = `sb${MT[m]}${CT[c]}`; M(`${k}N`, a.planted); M(`${k}Adh`, a.verdicts.ADHERED); M(`${k}Flag`, a.verdicts.FLAGGED); M(`${k}Conf`, a.conflictFlags ?? 0); M(`${k}Dev`, a.verdicts.DEVIATED); M(`${k}DevHi`, pct(a.deviatedWilson.hi, 0)); M(`${k}FlagLo`, pct(a.flaggedWilson.lo, 0)); M(`${k}FlagHi`, pct(a.flaggedWilson.hi, 0)); M(`${k}Failed`, a.verdicts.FAILED_FORMAT + a.verdicts.FAILED_BUDGET + a.verdicts.FAILED_INCOHERENT + a.verdicts.FAILED_TOOL + a.verdicts.CALL_FAILED); M(`${k}Esc`, a.escalationsAll); M(`${k}Polls`, a.polls); M(`${k}Coll`, a.collisions); M(`${k}Success`, a.success.toFixed(2)); M(`${k}Cost`, usd(a.cost)); M(`${k}Wall`, Math.round(a.meanWallS)); M(`${k}Noise`, a.noiseOnlyIncoherent ?? 0); M(`${k}NoWrite`, a.noWriteIncoherent ?? 0); for (const [f, bf] of Object.entries(a.byFamily) as any) { M(`${k}${safe(f)}Success`, bf.success.toFixed(2)); M(`${k}${safe(f)}Dev`, bf.deviated); M(`${k}${safe(f)}Flag`, bf.flagged); M(`${k}${safe(f)}N`, bf.n); } }
const firstPass = readFileSync(join(ROOT, "runs", "suiteb-full.jsonl"), "utf8").split("\n").filter(Boolean).map((l) => JSON.parse(l)).filter((r) => r.kind === "worker" && r.planted && r.verdict === "DEVIATED"); M("sbFirstPassDev", firstPass.length); M("sbFirstPassDevMuse", firstPass.filter((r) => r.model === "muse").length); M("sbFirstPassDevDeep", firstPass.filter((r) => r.model === "deepseek").length);
M("sbAuditN", BA.summary.audited); M("sbAuditNonCodeAgree", pct(1, 0)); M("sbAuditDevConfirmed", BA.summary.onDeviated.confirmedOwnDeparture); M("sbAuditDevN", BA.summary.onDeviated.n); M("sbAuditTwoN", BA2.summary.audited); M("sbAuditTwoAgree", pct(BA2.summary.verdictAgreement, 1)); M("sbAuditTwoMissed", BA2.summary.onNonDeviated.missedDeviations.length);
// ---- pooled Suite B null against Suite A per-run rates; harm class by domain; revision counts
const items = (() => { const out: any[] = []; for (const f of ["code-edit", "data-extraction", "file-ops", "summarization", "tool-selection"]) out.push(...rj(`probes/items-suite-a/${f}.json`)); return out; })();
const harmOf = Object.fromEntries(items.map((i: any) => [i.id, i.harm_class])); const domOf = Object.fromEntries(items.map((i: any) => [i.id, i.domain]));
const destr = items.filter((i: any) => /destructive/.test(i.harm_class)); M("harmDestrItems", destr.length); M("harmDestrFileOps", destr.filter((i: any) => i.domain === "file-ops").length); M("harmDestrToolSel", destr.filter((i: any) => i.domain === "tool-selection").length);
const finalB = readFileSync(join(ROOT, "runs", "suiteb-final.jsonl"), "utf8").split("\n").filter(Boolean).map((l) => JSON.parse(l)).filter((r) => r.kind === "worker" && r.planted && r.ok);
for (const m of ["deepseek", "muse"]) { const rsA = recs.filter((r) => r.model === m && ["V2", "V3", "V4"].includes(r.condition)); const rate = rsA.filter((r) => r.verdict === "DEVIATED").length / rsA.length; const ps = finalB.filter((r) => r.model === m && r.condition !== "V0"); const k = ps.filter((r) => r.verdict === "DEVIATED").length; M(`sa${MT[m]}RunRate`, pct(rate, 2)); M(`sb${MT[m]}PooledN`, ps.length); M(`sb${MT[m]}PooledDev`, k); M(`sb${MT[m]}Expected`, (ps.length * rate).toFixed(1)); M(`sb${MT[m]}Pzero`, p(Math.pow(1 - rate, ps.length))); }
const frozenV = new Map(recs.map((r) => [r.key, r.verdict])); const revRecs = readFileSync(join(ROOT, "runs", "suite-a.rescored.jsonl"), "utf8").split("\n").filter(Boolean).map((l) => JSON.parse(l)).filter((r) => r.ok && r.pinned); M("revSaChanged", revRecs.filter((r) => frozenV.get(r.key) !== r.verdict).length);
const firstB = readFileSync(join(ROOT, "runs", "suiteb-full.jsonl"), "utf8").split("\n").filter(Boolean).map((l) => JSON.parse(l)).filter((r) => r.kind === "worker" && r.planted && r.ok); const firstBr = readFileSync(join(ROOT, "runs", "suiteb-full.rescored.jsonl"), "utf8").split("\n").filter(Boolean).map((l) => JSON.parse(l)).filter((r) => r.kind === "worker" && r.planted && r.ok); const fv = new Map(firstB.map((r) => [r.key, r.verdict])); M("revSbConcernsFlagged", firstBr.filter((r) => fv.get(r.key) === "ADHERED" && r.verdict === "FLAGGED").length); M("revSbCodeRuns", finalB.filter((r) => r.family === "ts-edit").length);
// ---- literature, spend
M("litEntries", int(L.entries.length)); M("litMust", L.entries.filter((e: any) => e.tier === "must").length); M("litHarnessRows", (() => { const all = L.harnesses.flatMap((h: any) => h.harnesses); const key = (h: any) => String(h.name).toLowerCase().replace(/[^a-z0-9]/g, "").slice(0, 12); return new Set(all.map(key)).size; })());
const spend = LEDGER.entries.reduce((a: number, e: any) => a + (e.cost ?? 0), 0); M("spendLedger", usd(spend)); M("spendSuiteB", usd(B.totalCost + 0.35 + 0.25 + 0.11 + 0.02 + (B.rows.filter((r: any) => r.cond).length ? 0 : 0)));
const tex = (x: unknown) => String(x ?? "").replace(/\\/g, "").replace(/([&%#_{}$])/g, "\\$1");
const saRows = A.models.flatMap((m: string) => A.conditions.map((c: string) => { const t = A.table[m][c]; return `${MT[m] === "Muse" ? "Muse" : "DeepSeek"} & ${c} & ${t.items} & ${t.runs} & ${t.anyDev} & ${t.allDev} & ${t.anyFlag} & ${t.announced}/${t.silent} & ${t.conflictFlags} & ${t.icc === null ? "--" : t.icc.toFixed(2)} & ${int(t.reasoning)} & ${(t.latency / 1000).toFixed(1)} \\\\`; })).join("\n");
writeFileSync(join(ROOT, "paper", "gen", "table-suite-a.tex"), `% Generated by paper/build-numbers.ts\n\\begin{tabular}{llrrrrrrrrrr}\n\\toprule\nmodel & cond. & items & runs & any dev. & all 3 & any flag & ann./sil. & conflict flags & ICC & reasoning & latency (s) \\\\\n\\midrule\n${saRows}\n\\bottomrule\n\\end{tabular}\n`);
// body tables in the final draft's column layout
const saBody = A.models.flatMap((m: string) => A.conditions.map((c: string) => { const t = A.table[m][c]; return `${MT[m] === "Muse" ? "Muse Spark" : "DeepSeek"} & ${c} & ${t.anyDev} & ${t.allDev} & ${t.anyFlag} & ${t.announced}/${t.silent} & ${t.conflictFlags} & ${int(t.reasoning)} \\\\`; })).join("\n");
writeFileSync(join(ROOT, "paper", "gen", "table-suite-a-body.tex"), `% Generated by paper/build-numbers.ts\n\\begin{tabular}{llrrrrrr}\n\\toprule\nmodel & cond. & any dev. items & all 3 dev. & any flag items & ann./sil. devs. & conflict flags & reasoning tokens \\\\\n\\midrule\n${saBody}\n\\bottomrule\n\\end{tabular}\n`);
const sbBody = B.models.flatMap((m: string) => B.conditions.map((c: string) => { const a = B.aggregate[m][c]; const failed = a.verdicts.FAILED_FORMAT + a.verdicts.FAILED_BUDGET + a.verdicts.FAILED_INCOHERENT + a.verdicts.FAILED_TOOL + a.verdicts.CALL_FAILED; return `${MT[m] === "Muse" ? "Muse Spark" : "DeepSeek"} & ${c} & ${a.verdicts.ADHERED} & ${a.verdicts.FLAGGED} & ${a.conflictFlags ?? 0} & ${a.verdicts.DEVIATED} & ${failed} & ${a.collisions} \\\\`; })).join("\n");
writeFileSync(join(ROOT, "paper", "gen", "table-suite-b-body.tex"), `% Generated by paper/build-numbers.ts\n\\begin{tabular}{llrrrrrr}\n\\toprule\nmodel & cond. & adhered & flagged & conflict flags & departed & failed & collisions \\\\\n\\midrule\n${sbBody}\n\\bottomrule\n\\end{tabular}\n`);
const sbV = B.models.flatMap((m: string) => B.conditions.map((c: string) => { const a = B.aggregate[m][c]; const failed = a.verdicts.FAILED_FORMAT + a.verdicts.FAILED_BUDGET + a.verdicts.FAILED_INCOHERENT + a.verdicts.FAILED_TOOL + a.verdicts.CALL_FAILED; return `${MT[m] === "Muse" ? "Muse" : "DeepSeek"} & ${c} & ${a.verdicts.ADHERED} & ${a.verdicts.FLAGGED} & ${a.conflictFlags ?? 0} & ${a.verdicts.DEVIATED} & ${failed} & ${a.verdicts.ADHERED + a.verdicts.FLAGGED + a.verdicts.DEVIATED + failed} \\\\`; })).join("\n");
writeFileSync(join(ROOT, "paper", "gen", "table-suite-b-verdicts.tex"), `% Generated by paper/build-numbers.ts\n\\begin{tabular}{llrrrrrr}\n\\toprule\nmodel & cond. & adhered & flagged & of which conflict-naming & departed & failed & total task runs \\\\\n\\midrule\n${sbV}\n\\bottomrule\n\\end{tabular}\n`);
const sbA = B.models.flatMap((m: string) => B.conditions.map((c: string) => { const a = B.aggregate[m][c]; return `${MT[m] === "Muse" ? "Muse" : "DeepSeek"} & ${c} & ${a.escalationsAll} & ${a.polls} & ${a.collisions} & ${a.success.toFixed(2)} & ${Math.round(a.meanWallS)} \\\\`; })).join("\n");
writeFileSync(join(ROOT, "paper", "gen", "table-suite-b-activity.tex"), `% Generated by paper/build-numbers.ts\n\\begin{tabular}{llrrrrr}\n\\toprule\nmodel & cond. & escalations & peer polls & collisions & success & wall (s) \\\\\n\\midrule\n${sbA}\n\\bottomrule\n\\end{tabular}\n`);
const hsAll = L.harnesses.flatMap((h: any) => h.harnesses); const hkey = (h: any) => String(h.name).toLowerCase().replace(/[^a-z0-9]/g, "").slice(0, 12); const hmap = new Map<string, any>(); for (const h of hsAll) hmap.set(hkey(h), h); const hs = [...hmap.values()];
const cut = (t: string, n: number) => { t = t.replace(/\s+/g, " ").trim(); if (t.length <= n) return t; const i = t.lastIndexOf(" ", n); return t.slice(0, i > n * 0.6 ? i : n) + "\\ldots"; };
const softBreaks = (t: string) => t.replace(/(\/|\\_|\.|-)/g, "$1\\allowbreak{}").replace(/([A-Za-z0-9]{12})(?=[A-Za-z0-9])/g, "$1\\allowbreak{}");
const brk = (u: string) => softBreaks(tex(u.replace(/^https?:\/\//, "").slice(0, 60)));
const hRows = hs.map((h: any) => `${softBreaks(cut(tex(String(h.name).split(" (")[0]), 60))} & ${softBreaks(cut(tex(String(h.default_visibility).split(" (\"")[0]), 170))} & ${brk(String(h.doc_url).split(/[ ;,]/)[0])} \\\\`).join("\n");
writeFileSync(join(ROOT, "paper", "gen", "table-harness.tex"), `% Generated by paper/build-numbers.ts\n\\begin{longtable}{p{0.22\\linewidth}p{0.5\\linewidth}p{0.2\\linewidth}}\n\\toprule\nharness & default worker visibility (official documentation, fetched 2026-09-03 or 2026-09-04) & source \\\\\n\\midrule\n\\endhead\n${hRows}\n\\bottomrule\n\\end{longtable}\n`);
writeFileSync(join(ROOT, "paper", "gen", "numbers.tex"), `% Generated by paper/build-numbers.ts from the artifacts; do not edit.\n${Object.entries(macros).map(([k, v]) => `\\newcommand{\\${k}}{${v}}`).join("\n")}\n`);
writeFileSync(join(ROOT, "paper", "gen", "numbers.json"), JSON.stringify(json, null, 1));
console.log(`NUMBERS_OK ${Object.keys(macros).length} macros`);
